INFO 2025-03-26 20:46:59 FaceAlignModelLoader.py: 22] Start to analyze the face landmark model, model path: models, model category: face_alignment，model name: face_alignment_1.0
INFO 2025-03-26 20:46:59 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2025-03-26 20:46:59 FaceAlignModelLoader.py: 35] Successfully loaded the face landmark model!
INFO 2025-03-26 20:46:59 FaceParsingModelLoader.py: 17] Start to analyze the face parsing model, model path: models, model category: face_parsing，model name: face_parsing_1.0
INFO 2025-03-26 20:46:59 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
ERROR 2025-03-26 20:46:59 FaceParsingModelLoader.py: 29] The model failed to load, please check the model path: models/face_parsing/face_parsing_1.0/face_parsing.farl.lapa.main_ema_136500_jit191.pt!
INFO 2025-03-27 22:19:07 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
ERROR 2025-03-27 22:19:07 FaceDetModelLoader.py: 30] The model failed to load, please check the model path: models\face_detection\face_detection_1.0\face_detection_retina.pkl!
INFO 2025-03-27 22:20:23 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
ERROR 2025-03-27 22:20:23 FaceDetModelLoader.py: 30] The model failed to load, please check the model path: models\face_detection\face_detection_1.0\face_detection_retina.pkl!
INFO 2025-03-27 22:21:06 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
ERROR 2025-03-27 22:21:06 FaceDetModelLoader.py: 30] The model failed to load, please check the model path: models\face_detection\face_detection_1.0\face_detection_retina.pkl!
INFO 2025-03-27 22:21:25 FaceDetModelLoader.py: 16] Start to analyze the face detection model, model path: models, model category: face_detection, model name: face_detection_1.0
INFO 2025-03-27 22:21:25 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
ERROR 2025-03-27 22:21:25 FaceDetModelLoader.py: 30] The model failed to load, please check the model path: models\face_detection\face_detection_1.0\face_detection_retina.pkl!
INFO 2025-03-27 22:30:05 FaceDetModelLoader.py: 18] Start to analyze the face detection model, model path: models, model category: face_detection, model name: face_detection_1.0
INFO 2025-03-27 22:30:05 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
ERROR 2025-03-27 22:30:05 FaceDetModelLoader.py: 33] The model failed to load, please check the model path: models\face_detection\face_detection_1.0\face_detection_retina.pkl!
INFO 2025-03-27 22:36:33 FaceDetModelLoader.py: 18] Start to analyze the face detection model, model path: models, model category: face_detection, model name: face_detection_1.0
INFO 2025-03-27 22:36:33 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
ERROR 2025-03-27 22:36:33 FaceDetModelLoader.py: 33] The model failed to load, please check the model path: models\face_detection\face_detection_1.0\face_detection_retina.pkl!
INFO 2025-03-27 22:36:42 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
ERROR 2025-03-27 22:36:42 FaceRecModelLoader.py: 26] The model failed to load, please check the model path: models\face_recognition\face_recognition_1.0\face_recognition_mv.pkl!
INFO 2025-03-27 22:38:18 FaceDetModelLoader.py: 18] Start to analyze the face detection model, model path: models, model category: face_detection, model name: face_detection_1.0
INFO 2025-03-27 22:38:18 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
ERROR 2025-03-27 22:38:18 FaceDetModelLoader.py: 33] The model failed to load, please check the model path: models\face_detection\face_detection_1.0\face_detection_retina.pkl!
INFO 2025-03-27 22:39:03 FaceDetModelLoader.py: 18] Start to analyze the face detection model, model path: models, model category: face_detection, model name: face_detection_1.0
INFO 2025-03-27 22:39:03 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
ERROR 2025-03-27 22:39:03 FaceDetModelLoader.py: 33] The model failed to load, please check the model path: models\face_detection\face_detection_1.0\face_detection_retina.pkl!
INFO 2025-03-27 22:46:54 FaceDetModelLoader.py: 18] Start to analyze the face detection model, model path: models, model category: face_detection, model name: face_detection_1.0
INFO 2025-03-27 22:46:54 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
ERROR 2025-03-27 22:46:54 FaceDetModelLoader.py: 33] The model failed to load, please check the model path: models\face_detection\face_detection_1.0\face_detection_retina.pkl!
INFO 2025-03-27 23:19:51 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
ERROR 2025-03-27 23:19:51 FaceAlignModelLoader.py: 31] The model failed to load, please check the model path: models\face_alignment\face_alignment_1.0\face_landmark_pfld.pkl!
INFO 2025-03-27 23:21:00 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
ERROR 2025-03-27 23:21:00 FaceAlignModelLoader.py: 31] The model failed to load, please check the model path: models\face_alignment\face_alignment_1.0\face_landmark_pfld.pkl!
INFO 2025-03-27 23:22:04 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2025-03-27 23:22:04 FaceAlignModelLoader.py: 35] Successfully loaded the face landmark model!
INFO 2025-03-27 23:22:23 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
ERROR 2025-03-27 23:22:23 FaceAlignModelLoader.py: 31] The model failed to load, please check the model path: models\face_alignment\face_alignment_1.0\face_landmark_pfld.pkl!
INFO 2025-03-27 23:24:01 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2025-03-27 23:24:02 FaceAlignModelLoader.py: 35] Successfully loaded the face landmark model!
INFO 2025-03-27 23:33:46 FaceAlignModelLoader.py: 22] Start to analyze the face landmark model, model path: models, model category: face_alignment, model name: face_alignment_1.0
INFO 2025-03-27 23:33:46 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2025-03-27 23:33:46 FaceAlignModelLoader.py: 36] Successfully loaded the face landmark model!
INFO 2025-03-27 23:38:22 FaceAlignModelLoader.py: 23] Start to analyze the face landmark model, model path: models, model category: face_alignment, model name: face_alignment_1.0
INFO 2025-03-27 23:38:22 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2025-03-27 23:38:22 FaceAlignModelLoader.py: 37] Successfully loaded the face landmark model!
INFO 2025-03-27 23:39:01 FaceAlignModelLoader.py: 23] Start to analyze the face landmark model, model path: models, model category: face_alignment, model name: face_alignment_1.0
INFO 2025-03-27 23:39:01 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
ERROR 2025-03-27 23:39:01 FaceAlignModelLoader.py: 33] The model failed to load, please check the model path: models\face_alignment\face_alignment_1.0\face_landmark_pfld.pkl!
INFO 2025-03-27 23:44:34 FaceAlignModelLoader.py: 23] Start to analyze the face landmark model, model path: models, model category: face_alignment, model name: face_alignment_1.0
INFO 2025-03-27 23:44:34 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
ERROR 2025-03-27 23:44:34 FaceAlignModelLoader.py: 33] The model failed to load, please check the model path: models\face_alignment\face_alignment_1.0\face_landmark_pfld.pkl!
INFO 2025-03-27 23:51:51 FaceAlignModelLoader.py: 24] Start to analyze the face landmark model, model path: models, model category: face_alignment, model name: face_alignment_1.0
INFO 2025-03-27 23:51:51 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
ERROR 2025-03-27 23:51:51 FaceAlignModelLoader.py: 34] The model failed to load, please check the model path: models\face_alignment\face_alignment_1.0\face_landmark_pfld.pkl!
INFO 2025-03-27 23:55:22 FaceAlignModelLoader.py: 24] Start to analyze the face landmark model, model path: models, model category: face_alignment, model name: face_alignment_1.0
INFO 2025-03-27 23:55:22 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
ERROR 2025-03-27 23:55:22 FaceAlignModelLoader.py: 34] The model failed to load, please check the model path: models\face_alignment\face_alignment_1.0\face_landmark_pfld.pkl!
INFO 2025-03-28 00:07:03 FaceAlignModelLoader.py: 24] Start to analyze the face landmark model, model path: models, model category: face_alignment, model name: face_alignment_1.0
INFO 2025-03-28 00:07:03 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
ERROR 2025-03-28 00:07:03 FaceAlignModelLoader.py: 34] The model failed to load, please check the model path: models\face_alignment\face_alignment_1.0\face_landmark_pfld.pkl!
INFO 2025-03-28 00:13:34 FaceAlignModelLoader.py: 24] Start to analyze the face landmark model, model path: models, model category: face_alignment, model name: face_alignment_1.0
INFO 2025-03-28 00:13:34 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
ERROR 2025-03-28 00:13:34 FaceAlignModelLoader.py: 34] The model failed to load, please check the model path: models\face_alignment\face_alignment_1.0\face_landmark_pfld.pkl!
INFO 2025-03-28 00:14:12 FaceAlignModelLoader.py: 24] Start to analyze the face landmark model, model path: models, model category: face_alignment, model name: face_alignment_1.0
INFO 2025-03-28 00:14:12 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
